name: Deploy VitePress site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# 允许同一个 group 的任务排队，但如果有了新 Push，直接干掉旧的，防止产物堆积
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # 任务 1：负责编译和上传产物
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5              

      - name: Setup pnpm
        uses: pnpm/action-setup@v4            

      - name: Setup Node
        uses: actions/setup-node@v5           
        with:
          node-version: 24                    
          cache: pnpm

      - name: Force git to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm docs:build

      - name: Setup Pages
        uses: actions/configure-pages@v5       

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4 
        with:
          path: docs/.vitepress/dist

  # 任务 2：独立部署任务，只有在 build 成功后才触发
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build # 确保 build 成功后再跑
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4